// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO0k3j3eLpmUxG_WFLG1KD8y5AFGXjpcM',
    appId: '1:983571048128:web:606bab7815d189e2cbaf25',
    messagingSenderId: '983571048128',
    projectId: 'otra-copa-py-2026',
    authDomain: 'otra-copa-py-2026.firebaseapp.com',
    storageBucket: 'otra-copa-py-2026.firebasestorage.app',
    measurementId: 'G-DCVM78JT46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAke8Z6D7Yd3kG9kbnnXeYXbwjksp8GRXM',
    appId: '1:983571048128:android:ccd7e5497a4ffc32cbaf25',
    messagingSenderId: '983571048128',
    projectId: 'otra-copa-py-2026',
    storageBucket: 'otra-copa-py-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuPSzeJBzkF1fEHfTsvOwoBV6EPN_Y99U',
    appId: '1:983571048128:ios:0af223099c5adeb5cbaf25',
    messagingSenderId: '983571048128',
    projectId: 'otra-copa-py-2026',
    storageBucket: 'otra-copa-py-2026.firebasestorage.app',
    iosBundleId: 'com.example.otraCopa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuPSzeJBzkF1fEHfTsvOwoBV6EPN_Y99U',
    appId: '1:983571048128:ios:0af223099c5adeb5cbaf25',
    messagingSenderId: '983571048128',
    projectId: 'otra-copa-py-2026',
    storageBucket: 'otra-copa-py-2026.firebasestorage.app',
    iosBundleId: 'com.example.otraCopa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO0k3j3eLpmUxG_WFLG1KD8y5AFGXjpcM',
    appId: '1:983571048128:web:7330b95a3c052517cbaf25',
    messagingSenderId: '983571048128',
    projectId: 'otra-copa-py-2026',
    authDomain: 'otra-copa-py-2026.firebaseapp.com',
    storageBucket: 'otra-copa-py-2026.firebasestorage.app',
    measurementId: 'G-51ZW7NN56Z',
  );
}
